eca_float_or_token:
  label: 'Float or Token'
  class: '\Drupal\eca\Plugin\DataType\FloatOrToken'
eca_integer_or_token:
  label: 'Integer or Token'
  class: '\Drupal\eca\Plugin\DataType\IntegerOrToken'
